"""replace_price_unique_constraint_to_instrument_date

Revision ID: 1ea9d13fd395
Revises: e14dc1438a61
Create Date: 2026-08-19 16:11:39.539097
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1ea9d13fd395'
down_revision: Union[str, None] = 'e14dc1438a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_prices_instrument_date_time'), 'prices', type_='unique')
    op.create_unique_constraint('uq_prices_instrument_date', 'prices', ['instrument_id', 'price_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_prices_instrument_date', 'prices', type_='unique')
    op.create_unique_constraint(op.f('uq_prices_instrument_date_time'), 'prices', ['instrument_id', 'price_date', 'price_time'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
