"""add_ohlc_to_prices

Revision ID: 784fe66c1b73
Revises: 0ad1f226a713
Create Date: 2026-08-20 17:29:42.571869
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '784fe66c1b73'
down_revision: Union[str, None] = '0ad1f226a713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('open_price', sa.Float(), nullable=True))
    op.add_column('prices', sa.Column('high_price', sa.Float(), nullable=True))
    op.add_column('prices', sa.Column('low_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'low_price')
    op.drop_column('prices', 'high_price')
    op.drop_column('prices', 'open_price')
    # ### end Alembic commands ###
