"""add_instruments_and_prices_tables

Revision ID: e14dc1438a61
Revises: 0002
Create Date: 2026-08-19 15:09:31.051675
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e14dc1438a61'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('exchange', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Text(), nullable=False),
    sa.Column('price_time', sa.Text(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('day_change_pct', sa.Float(), nullable=True),
    sa.Column('week_change_pct', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'price_date', 'price_time', name='uq_prices_instrument_date_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices')
    op.drop_table('instruments')
    # ### end Alembic commands ###
